services:
  postgres:
    image: pgvector/pgvector:pg17
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
  # agentnexus:
  #   image: agentnexus:latest
  #   restart: always
  #   ports:
  #     - 3000:3000
